# Generated by Django 3.2.6 on 2021-08-25 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_time',
            new_name='created_time',
        ),
    ]
